### PR TITLE
fixed events-controller + posts-controller, refactoring *_filter to *_action

### PR DESCRIPTION
**Pull request by mattherick**
1) Bugfix: There was an error in the ical action in the events controller.
2) Bugfix: There was an error in the show action in the posts controller => everybody could see posts with status "draft" if they know the exact url.
3) Refactoring: changed *_filter to *_action (like before_filter to before_action)

### CODE REVIEW

**Comment by bborn** [comment]
Looks great. Can you please add a test for the two bugfixes?

**Comment by mattherick** [comment]
How could I execute the tests locally? Sorry.. :-)

**Comment by bborn** [comment]
No problem: 


```
bundle install
rake db:migrate
rake test
```


See also: https://github.com/bborn/communityengine/pull/280#issuecomment-69792075

**Comment by mattherick** [comment]
Where do I have to execute your commands? Directly in the gem root directory?

**Comment by bborn** [comment]
Yeah, you'd want to clone the CE repo into a working directory, and then
execute the commands there. CE comes with a dummy app in its test directory
that lets you run tests.

**Comment by mattherick** [comment]
Okay, I added the missing tests.
The bug in the posts-controller was already tested - but with an incomplete fixture..I added a new one.

**Comment by bborn** [comment]
Cool. Thanks!

**Pull request merged**
